
services:
  backend:
    build: ./backend
    image: wo_tracker_backend:latest
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=tracker
      - DB_PASSWORD=tracker
      - DB_NAME=tracker
    depends_on:
      - postgres
    command: sh -c "npm run build && npm run start:prod"

  frontend:
    build: ./frontend
    image: wo_tracker_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env
    command: sh -c "npm run build && npm run start:prod"

  postgres:
    image: postgres:15
    volumes:
      - wo_tracker:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "15432:5432"
    env_file:
      - .env

volumes:
  wo_tracker:
